### ISSUE TITLE
server 4.3 server properties values are differently typed

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_capability_indexing#77]
In iRODS 4.2, getting an item  from server properties involved conversions and exception-processing related to the `boost::any` type.

We now store these values as JSON strings, meaning we parse in a structure via `nlohmann::json` instead, with the attendant changes in the exception `catch` signatures and blocks.

**Comment by korydraughn** [comment]
@d-w-moore Is this complete/done?

**Comment by d-w-moore** [comment]
@korydraughn I have to refresh my memory on this one... studying

**Comment by alanking** [comment]
Seems related to these...

https://github.com/irods/irods/issues/5434
https://github.com/irods/irods/issues/5602

**Comment by korydraughn** [comment]
And given the commits against this issue, would you say the issue has been resolved?

**Comment by alanking** [comment]
Just eyeballing it... I would say yes. I think it's mainly related to the move from `boost::any` to `nlohmann::json` for the server properties, so, I would expect that we would be having build problems if it wasn't resolved. Thoughts?

**Comment by korydraughn** [comment]
I agree. The commits hint that this can be closed.

@d-w-moore If you determine the work for this is completed, please proceed with closing it.

**Comment by d-w-moore** [comment]
I agree, especially as your tests seem to be mostly passing.
